version: '3.7'

networks:
  back:

services:
  mongodb:
    image: mongo:6.0
    ports:
      - ${MONGO_EXPOSE_PORT}:27017
    volumes:
      - mongodb_data:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - back
  app:
    build: ./
    depends_on:
      - mongodb
    command: "serve -c ./config/config.yml"
    environment:
      MONGO_EXPOSE_PORT: ${MONGO_EXPOSE_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      TICKERINTERVALSECONDS: ${TICKERINTERVALSECONDS}
    ports:
      - ${API_EXPOSE_PORT}:8888
    networks:
      - back

volumes:
  mongodb_data:
    driver: local